version: '3.8'
services:
    api:
        build: ./api
        container_name: vidly_api
        ports:
            - 3000:3000
        volumes:
            - ./api:/app
            - /app/node_modules
        depends_on:
            - db
        environment:
            - NODE_ENV=development
            - DEBUG=app:startup
            - DB_SERVER_NAME=db
            - JWT_KEY="devEnvKey12345"
            - PORT=3000
    api-tests:
        build:
            context: ./api
            dockerfile: Dockerfile-test
        container_name: vidly_api_tests
        volumes:
            - ./api:/app
            - /app/node_modules
        depends_on:
            - db
        environment:
            - NODE_ENV=test
            - DEBUG=app:startup
            - DB_SERVER_NAME=db
            - JWT_KEY="testEnvKey12345"
            - PORT=5000
    db:
        image: mongo:4.0-xenial
        container_name: vidly_db
        ports:
            - 27017:27017
        volumes:
            - mongodata:/data/db

volumes:
    mongodata:
